DATA:
  IMAGE_SIZE: (112, 224)
  DIR: cropped_image
    
TRAIN_PARAMS:
  EPOCHS : 100
  BATCH_SIZE : 1024
    
MODEL_PARAMS:
  d_model : 512
  nhead : 4
  num_layers : 1
  dim_feedforward : 2048
  dropout : 0.1