DATA:
  IMAGE_SIZE: (112, 448)
  DIR: cropped_image
    
TRAIN_PARAMS:
  EPOCHS : 50
  BATCH_SIZE : 512
    
MODEL_PARAMS:
  d_model : 384
  nhead : 4
  num_layers : 4
  dim_feedforward : 2048
  dropout : 0.1